//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeminarManagementEntities1 : DbContext
    {
        public SeminarManagementEntities1()
            : base("name=SeminarManagementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Organizer> Organizers { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Seminar> Seminars { get; set; }
    }
}
