//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminar
    {
        public int SeminarID { get; set; }
        public Nullable<int> OrganizerID { get; set; }
        public string SeminarTitle { get; set; }
        public string SeminarDescription { get; set; }
        public string SeminarType { get; set; }
        public Nullable<System.DateTime> SeminarDate { get; set; }
        public string SeminarStartTime { get; set; }
        public string SeminarEndTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
